# Generated by Django 3.2.8 on 2021-10-07 14:16

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=19, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=29, verbose_name='Фамилия')),
                ('data_joined', models.DateField(auto_now_add=True, db_index=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=122, unique=True, verbose_name='Название группы')),
                ('is_headman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headman', to=settings.AUTH_USER_MODEL, verbose_name='Староста')),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
            ],
            options={
                'verbose_name': 'Под группа',
                'verbose_name_plural': 'Под группы',
                'ordering': ('super_group__name', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.group',),
        ),
        migrations.CreateModel(
            name='SuperGroup',
            fields=[
            ],
            options={
                'verbose_name': ' Над группа',
                'verbose_name_plural': 'Над группы',
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.group',),
        ),
        migrations.AddField(
            model_name='group',
            name='super_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.supergroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supergroup', to='main.subgroup'),
        ),
    ]
