# Generated by Django 3.2.8 on 2021-12-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supergroup',
            options={'ordering': ('name',), 'verbose_name': 'Над группа', 'verbose_name_plural': 'Над группы'},
        ),
    ]
